
declare -a experiments=(
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step49.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step59.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step69.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/carrot/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/carrot/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/carrot/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/carrot/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/carrot/step49.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/carrot/step59.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/carrot/step69.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/spoon/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/spoon/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/spoon/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/spoon/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/spoon/step49.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/spoon/step59.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/spoon/step69.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/eggplant/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/eggplant/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/eggplant/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/eggplant/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/eggplant/step49.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/eggplant/step59.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/eggplant/step69.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/joint/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/joint/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/joint/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/joint/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/joint/step49.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/joint/step59.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-joint-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/joint/step69.pt"
)

# declare -a experiments=(
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint/step79.pt"
# )



# declare -a experiments=(
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug6-faster-bridge-stack-lr5e-6-mini128/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb6_mini128/bridge/stack/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-stack-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-carrot-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-spoon-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-eggplant-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant/step79.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/actor/global_step_59" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint/step59.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/actor/global_step_69" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint/step69.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/SimpleVLA-RL/exp1-openvla_oft_fb_wm_ffp-full-fixedbug5-faster-bridge-joint-lr5e-6-mini128/actor/global_step_79" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint/step79.pt"
# )


# declare -a experiments=(
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack-fa/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack-fa/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack-fa/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack-fa/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-stack/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/stack-fa/step49.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot-fa/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot-fa/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot-fa/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot-fa/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-carrot/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/carrot-fa/step49.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon-fa/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon-fa/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon-fa/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon-fa/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-spoon/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/spoon-fa/step49.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant-fa/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant-fa/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant-fa/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant-fa/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-eggplant/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/eggplant-fa/step49.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint-fa/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint-fa/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint-fa/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint-fa/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/SimpleVLA-RL/exp2-openvla_oft_fb_wm_kl-full-fixedbug2-faster-bridge-joint/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts_openvla_fb5_mini128/bridge/joint-fa/step49.pt"
# )

num_experiments=${#experiments[@]}

for (( i=0; i<${num_experiments}; i+=2 )); do
    model_path=${experiments[i]}
    merge_path=${experiments[i+1]}

    bash examples/exp/OpenVLAOFT_exp/merge_ckpts/merge_bridge_batch.sh "${model_path}" "${merge_path}"
    ray stop --force
    echo "############################################################"
    echo "##                                                        ##"
    echo "##  实验 ${merge_path} 已完成"
    echo "##                                                        ##"
    echo "############################################################"
    echo ""
    echo ""
done

echo "所有实验已完成！"