
# declare -a experiments=(
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few/step49.pt"
# )

# declare -a experiments=(
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few/step49.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few/step49.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few/step49.pt"

#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few/step9.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few/step19.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few/step29.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few/step39.pt"
#     "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few/step49.pt"

# )


declare -a experiments=(
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few-cosmos/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few-cosmos/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few-cosmos/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few-cosmos/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-few-cosmos/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/carrot-fs-few-cosmos/step49.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few-cosmos/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few-cosmos/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few-cosmos/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few-cosmos/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-spoon-few-cosmos/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/spoon-fs-few-cosmos/step49.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few-cosmos/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few-cosmos/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few-cosmos/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few-cosmos/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-eggplant-few-cosmos/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/eggplant-fs-few-cosmos/step49.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few-cosmos/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few-cosmos/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few-cosmos/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few-cosmos/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-stack-filter-few-cosmos/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/stack-filter-fs-few-cosmos/step49.pt"

    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/actor/global_step_9" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few-cosmos/step9.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/actor/global_step_19" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few-cosmos/step19.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/actor/global_step_29" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few-cosmos/step29.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/actor/global_step_39" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few-cosmos/step39.pt"
    "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster-bridge-joint-filter-few-cosmos/actor/global_step_49" "/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/work_dirs/merged_ckpts/bridge/joint-filter-fs-few-cosmos/step49.pt"

)




num_experiments=${#experiments[@]}

for (( i=0; i<${num_experiments}; i+=2 )); do
    model_path=${experiments[i]}
    merge_path=${experiments[i+1]}

    bash examples/exp/VLA-Adapter_exp/merge_ckpts/merge_bridge_batch.sh "${model_path}" "${merge_path}"
    ray stop --force
    echo "############################################################"
    echo "##                                                        ##"
    echo "##  实验 ${merge_path} 已完成"
    echo "##                                                        ##"
    echo "############################################################"
    echo ""
    echo ""
done

echo "所有实验已完成！"