set -x
# apt install ffmpeg
export NCCL_DEBUG=WARN 
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export TOKENIZERS_PARALLELISM=true
export ACCELERATE_USE_FSDP=true
export FSDP_CPU_RAM_EFFICIENT_LOADING=true
# export MUJOCO_GL="osmesa"
export MUJOCO_GL="egl"
# export MUJOCO_GL="glx"
# export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6

# export CUDA_LAUNCH_BLOCKING=1
# export TORCH_USE_CUDA_DSA=1
# export MUJOCO_GL=egl

PROJECT_NAME='SimpleVLA-RL'
EXPERIMENT_NAME='gen_rm_for_wm_spatial_repeat'
# For openvla-oft Libero-Long traj1 SFT or traj all SFT models can be find in https://huggingface.co/collections/Haozhan72/simplevla-rl-6833311430cd9df52aeb1f86
SFT_MODEL_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/VLA-Adapter/outputs/configs+libero_spatial_no_noops+b8+lr-0.0001+lora-r64+dropout-0.0--image_aug--VLA-Adapter--libero_spatial_no_noops----10000_chkpt"
# SFT_MODEL_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/VLA-Adapter/outputs/configs+libero_10_no_noops+b8+lr-0.0001+lora-r64+dropout-0.0--image_aug--VLA-Adapter--libero_10_no_noops----150000_chkpt"
# SFT_MODEL_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/VLA-Adapter/outputs/configs+libero_10_no_noops+b8+lr-0.0001+lora-r64+dropout-0.0--image_aug--VLA-Adapter--libero_10_no_noops----100000_chkpt"
CKPT_PATH="work_dirs/$PROJECT_NAME/$EXPERIMENT_NAME"
# LOAD_MODEL_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/work_dirs/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster/SimpleVLA-RL/exp1-vla_adapter_wm_ffp-full-fixedbug-faster/actor/global_step_89"
# DATASET_NAME can be libero_10 (libero_Long), libero_90, libero_spatial, libero_object, libero_goal
# DATASET_NAME="libero_10"
DATASET_NAME="libero_spatial"
DATASET_PATH="/inspire/ssd/project/robotsimulation/public/data/LIBERO-datasets"
VLA_NAME="vla-adapter"
NUM_GPUS=8
# If you want to use 2*8 GPU to RL. Set NUM_NODES=2
NUM_NODES=1
ALIGN_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl/align.json"

# DIT_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/world_model/ActionWorldModel/checkpoints/predict2_video2world_2b_action_conditioned_finetuning_2025-09-13_12-36-12/checkpoints/model/iter_000042000.pt"
# DIT_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/world_model/ActionWorldModel/checkpoints/predict2_video2world_2b_action_conditioned_finetuning_2025-09-14_03-49-19/checkpoints/model/iter_000080000.pt"
# DIT_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/world_model/ActionWorldModel/checkpoints/predict2_video2world_2b_action_conditioned_finetuning_2025-09-14_03-49-19/checkpoints/model/iter_000118000.pt"
# DIT_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/world_model/ActionWorldModel/checkpoints/predict2_video2world_2b_action_conditioned_finetuning_2025-09-14_03-49-19/checkpoints/model/iter_000196000.pt"
# DIT_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/world_model/ActionWorldModel/checkpoints/predict2_video2world_2b_action_conditioned_finetuning_2025-09-14_03-49-19/checkpoints/model/iter_000292000.pt"
DIT_PATH="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/world_model/ActionWorldModel/checkpoints/pretrain/predict2_video2world_2b_action_conditioned_finetuning_libero_2025-10-22_01-04-32/checkpoints/model/iter_000034000.pt"
VAE_FOLDER="/inspire/ssd/project/robotsimulation/public/users/zhangjiahui/vla-rl-dev/world_model/ActionWorldModel"

HYDRA_FULL_ERROR=1 python -m verl_vla.trainer.main_ppo \
    data.task_suite_name=$DATASET_NAME \
    data.libero_raw_data_dir=$DATASET_PATH \
    data.num_trials_per_task=50 \
    data.n_samples=8 \
    data.filter_accuracy=True \
    data.accuracy_lower_bound=0.0 \
    data.accuracy_upper_bound=1.0 \
    data.oversample_factor=1 \
    data.train_batch_size=32 \
    data.val_batch_size=496 \
    data.max_prompt_length=256 \
    data.max_response_length=128 \
    actor_rollout_ref.model.path=$SFT_MODEL_PATH \
    actor_rollout_ref.model.load_ckpt=$LOAD_MODEL_PATH \
    actor_rollout_ref.model.vla=$VLA_NAME \
    actor_rollout_ref.model.action_token_len=7 \
    actor_rollout_ref.model.action_chunks_len=20 \
    actor_rollout_ref.actor.optim.lr=5e-6 \
    actor_rollout_ref.actor.optim.warmup_style=constant \
    actor_rollout_ref.actor.optim.params=full \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size=8 \
    actor_rollout_ref.actor.use_dynamic_bsz=False \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.grad_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.fsdp_config.model_dtype=bfloat16 \
    actor_rollout_ref.actor.grad_clip=1 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.num_images_in_input=1 \
    actor_rollout_ref.actor.traj_mini_batch_size=15 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.dlogp_clamp=True \
    actor_rollout_ref.actor.dlogp_clamp_max=4.0 \
    actor_rollout_ref.actor.dlogp_clamp_min=-4.0 \
    actor_rollout_ref.actor.kl_loss_type=kl_ffp \
    actor_rollout_ref.actor.k_baseline_eta=0.1 \
    actor_rollout_ref.actor.kl_loss_coef=0.04 \
    algorithm.kl_ctrl.kl_coef=0.04 \
    actor_rollout_ref.model.enable_gradient_checkpointing=False \
    actor_rollout_ref.model.use_remove_padding=False \
    actor_rollout_ref.actor.entropy_coeff=0. \
    actor_rollout_ref.actor.unnorm_key=$DATASET_NAME \
    actor_rollout_ref.rollout.num_images_in_input=1 \
    actor_rollout_ref.rollout.val_micro_batch_size=8 \
    actor_rollout_ref.rollout.temperature=1.6 \
    actor_rollout_ref.rollout.experiment_name=$EXPERIMENT_NAME \
    actor_rollout_ref.rollout.micro_batch_size=1 \
    actor_rollout_ref.rollout.unnorm_key=$DATASET_NAME \
    actor_rollout_ref.rollout.model_family=openvla \
    actor_rollout_ref.rollout.task_suite_name=$DATASET_NAME \
    actor_rollout_ref.rollout.num_steps_wait=10 \
    actor_rollout_ref.rollout.pretrained_checkpoint=$SFT_MODEL_PATH \
    actor_rollout_ref.rollout.center_crop=True \
    actor_rollout_ref.rollout.max_prompt_length=512 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=hf \
    actor_rollout_ref.rollout.reward_type=vlm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.n_gpus_per_node=$NUM_GPUS \
    actor_rollout_ref.ref.log_prob_micro_batch_size=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    actor_rollout_ref.ref.vla=$VLA_NAME \
    actor_rollout_ref.ref.fsdp_config.model_dtype=bfloat16 \
    actor_rollout_ref.ref.unnorm_key=$DATASET_NAME \
    actor_rollout_ref.ref.fsdp_config.model_dtype=float32 \
    reward_model.type=vlm_serve \
    reward_model.vlm_input_num_frames=50 \
    reward_model.vote_n=5 \
    reward_model.vote_m=3 \
    reward_model.temperature=0.6 \
    reward_model.top_p=0.9 \
    reward_model.return_env_score=True \
    reward_model.env_rollout=True \
    reward_model.gen_data_for_wm_rm=True \
    actor_rollout_ref.ref.vla=$VLA_NAME \
    actor_rollout_ref.world_model.dit_path=$DIT_PATH \
    actor_rollout_ref.world_model.vae_folder=$VAE_FOLDER \
    actor_rollout_ref.world_model.num_sampling_step=10 \
    actor_rollout_ref.world_model.use_cuda_graphs=True \
    actor_rollout_ref.world_model.fsdp_config.model_dtype=bfloat16 \
    actor_rollout_ref.world_model.use_history=True \
    actor_rollout_ref.world_model.history_video_length=60 \
    actor_rollout_ref.world_model.env_rollout=True \
    trainer.logger=['console','tensorboard'] \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.default_local_dir=$CKPT_PATH/$PROJECT_NAME/$EXPERIMENT_NAME \
    trainer.n_gpus_per_node=$NUM_GPUS \
    trainer.nnodes=$NUM_NODES \
    trainer.save_freq=20 \
    trainer.test_freq=10 \
    trainer.total_epochs=1000 \
    trainer.val_only=False \
    ray_init.num_cpus=32 \
    algorithm.adv_estimator=grpo \
    algorithm.adv_params.verifier_gamma=1.0 \
    algorithm.adv_params.reward_model_gamma=1.0 \
    trainer.runtime_env=$ALIGN_PATH \
    trainer.wandb_mode=online \
    trainer.val_before_train=False \
    2>&1 | tee -a "${EXPERIMENT_NAME}.log"

